name: update-dotnet-sdk

on:
  schedule:
    - cron:  '0 */6 * * *'
  workflow_dispatch:

jobs:
  update-dotnet-sdk:
    name: Update .NET SDK
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Update .NET SDK
      uses: martincostello/update-dotnet-sdk@v2
      if: ${{ github.repository_owner == 'justeat' }}
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
